In [37]:
import pandas as pd
import numpy as np
import nltk
import matplotlib.pyplot as plt
import spacy
nlp = spacy.load('en')

In [40]:
df = pd.read_csv('MoneyControl-First-1-20-Pages.csv')
df = df.iloc[:,1:]

In [41]:
titles = list(df.title)

In [33]:
titles = [token.lower() for token in titles]

In [38]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/hrishikesh/nltk_data...

True

In [39]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

In [43]:
df['scores'] = df['title'].apply(lambda review: sid.polarity_scores(review))
df['compound']  = df['scores'].apply(lambda score_dict: score_dict['compound'])
df['comp_score'] = df['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')

,time,Label,author,title,summary,description,article_text,url,scores,compound,comp_score
0,"April 13, 2020 12:04 PM IST",1,Sunil Matkar,Max Financial gains 5% on Max Life extending i...,Max Financial Services share price rallied 4.7...,Max Life-Yes Bank relationship has over the ye...,Max Financial Services share price rallied 4.7...,https://www.moneycontrol.com/news/business/mar...,"{'neg': 0.0, 'neu': 0.683, 'pos': 0.317, 'comp...",0.6249,pos
1,"April 13, 2020 08:55 PM IST",0,Kshitij Anand,Looking to invest in US market? Subscription f...,"On April 13, the company announced the launch ...",Motilal Oswal S&P 500® Index Fund will open fo...,If you wish to invest in companies based out o...,https://www.moneycontrol.com/news/business/mar...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos
2,"April 13, 2020 01:14 PM IST",0,Kshitij Anand,"Timing the market is not possible, but investo...",The choice of stocks vs mutual funds is always...,"Timing the market is not possible. However, at...","Timing the market is not possible. However, at...",https://www.moneycontrol.com/news/business/mar...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,pos
3,"April 13, 2020 02:34 PM IST",-1,Nishant Kumar,"Zee Entertainment share price plunges 14%, loo...",Zee Entertainment share price plunged over 14 ...,The company will extend financial and operatio...,Zee Entertainment share price plunged over 14 ...,https://www.moneycontrol.com/news/business/mar...,"{'neg': 0.0, 'neu': 0.567, 'pos': 0.433, 'comp...",0.8126,pos
4,"April 13, 2020 11:45 AM IST",-1,Sunil Matkar,Bandhan Bank share price slips 10% despite str...,Bandhan Bank share price fell nearly 10 percen...,The capital adequacy ratio of the bank at the ...,Bandhan Bank share price fell nearly 10 percen...,https://www.moneycontrol.com/news/business/mar...,"{'neg': 0.286, 'neu': 0.585, 'pos': 0.129, 'co...",-0.3991,neg

In [46]:
nlabs = []
for i in df.Label:
    if i < 0:
        nlabs.append('neg') 
    if i > 0:
        i = nlabs.append('pos')
    if i == 0:
        i = nlabs.append('pos')
df.Label = nlabs

In [47]:
df[['Label', 'comp_score']]

    Label comp_score
0     pos        pos
1     pos        pos
2     pos        pos
3     neg        pos
4     neg        neg
5     pos        pos
6     pos        pos
7     pos        pos
8     pos        pos
9     pos        pos
10    neg        pos
11    pos        neg
12    pos        neg
13    pos        pos
14    pos        pos
15    pos        pos
16    pos        pos
17    pos        pos
18    neg        neg
19    pos        pos
20    pos        pos
21    pos        pos
22    pos        neg
23    pos        pos
24    pos        pos
25    pos        pos
26    pos        pos
27    pos        pos
28    pos        pos
29    neg        pos
..    ...        ...
427   pos        pos
428   pos        pos
429   neg        pos
430   pos        pos
431   pos        pos
432   neg        neg
433   pos        neg
434   pos        neg
435   neg        pos
436   neg        neg
437   neg        neg
438   pos        pos
439   neg        pos
440   neg        pos
441   neg        pos
442   neg        pos
443   pos        pos
444   neg        pos
445   neg        pos
446   neg        pos
447   neg        neg
448   pos        neg
449   pos        pos
450   neg        pos
451   pos        pos
452   neg        pos
453   pos        neg
454   neg        pos
455   neg        pos
456   pos        pos

[457 rows x 2 columns]

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(df.Label, df.comp_score)

0.7024070021881839

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(df.Label, df.comp_score)

array([[ 62, 107],
       [ 29, 259]])

In [51]:
from sklearn.metrics import classification_report
print(classification_report(df['Label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.68      0.37      0.48       169
         pos       0.71      0.90      0.79       288

   micro avg       0.70      0.70      0.70       457
   macro avg       0.69      0.63      0.63       457
weighted avg       0.70      0.70      0.68       457